#!/bin/sh
set -e

case "$1" in
    configure)
        # pgedge user is created by pgedge-ai-dba-server (dependency)
        chown -R pgedge:pgedge /var/lib/pgedge/ai-dba-collector
        chown -R pgedge:pgedge /var/log/pgedge/ai-dba-collector

        chown root:pgedge /etc/pgedge/ai-dba-collector.yaml
        chmod 640 /etc/pgedge/ai-dba-collector.yaml

        touch /var/log/pgedge/ai-dba-collector/ai-dba-collector.log
        chown pgedge:pgedge /var/log/pgedge/ai-dba-collector/ai-dba-collector.log
        ;;
esac

#DEBHELPER#
