/*-------------------------------------------------------------------------
 *
 * pgEdge AI DBA Workbench - Chart Analysis Dialog
 *
 * Copyright (c) 2025 - 2026, pgEdge, Inc.
 * This software is released under The PostgreSQL License
 *
 * Dialog component for displaying AI-powered chart data analysis with
 * professional analytics aesthetic and markdown rendering
 *
 *-------------------------------------------------------------------------
 */

import React, { useEffect, useRef } from 'react';
import { Box, Typography, useTheme } from '@mui/material';
import { Psychology as PsychologyIcon } from '@mui/icons-material';
import {
    useChartAnalysis,
    ChartAnalysisInput,
} from '../hooks/useChartAnalysis';
import { ChartData, ChartAnalysisContext } from './Chart/types';
import { getIconColorSx } from './shared/MarkdownExports';
import {
    getConnectionBadgeSx,
    getDatabaseBadgeSx,
    getDatabaseTextSx,
    sxMonoSmall,
} from './analysisStyles';
import { BaseAnalysisDialog } from './shared/BaseAnalysisDialog';
import { downloadAsMarkdown } from '../utils/downloadMarkdown';
import { slugify } from '../utils/textHelpers';

const TOOL_LABELS = [
    'Preparing chart data',
    'Fetching server context',
    'Fetching timeline events',
    'Analyzing data',
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface ChartAnalysisDialogProps {
    open: boolean;
    onClose: () => void;
    isDark: boolean;
    analysisContext: ChartAnalysisContext;
    chartData: ChartData;
}

const ChartAnalysisDialog: React.FC<ChartAnalysisDialogProps> = ({
    open,
    onClose,
    isDark,
    analysisContext,
    chartData,
}) => {
    const theme = useTheme();
    const { analysis, loading, error, progressMessage, activeTools, analyze } =
        useChartAnalysis();

    // Trigger analysis once when dialog opens; ignore subsequent chartData
    // changes from dashboard polling while the dialog remains open.
    const hasTriggeredRef = useRef(false);

    useEffect(() => {
        if (open && !hasTriggeredRef.current) {
            hasTriggeredRef.current = true;
            if (!analysis) {
                const input: ChartAnalysisInput = {
                    metricDescription: analysisContext.metricDescription,
                    connectionId: analysisContext.connectionId,
                    connectionName: analysisContext.connectionName,
                    databaseName: analysisContext.databaseName,
                    timeRange: analysisContext.timeRange,
                    data: chartData,
                };
                analyze(input);
            }
        }
        if (!open) {
            hasTriggeredRef.current = false;
        }
    }, [open, analysis, analysisContext, chartData, analyze]);

    // Download analysis as markdown file
    const handleDownload = () => {
        if (!analysis) { return; }

        const timestamp = new Date().toISOString().split('T')[0];
        const slug = slugify(analysisContext.metricDescription || 'chart');
        const filename = `chart-analysis-${slug}-${timestamp}.md`;

        const connectionLine = analysisContext.connectionName
            ? `- **Connection:** ${analysisContext.connectionName}\n`
            : '';
        const databaseLine = analysisContext.databaseName
            ? `- **Database:** ${analysisContext.databaseName}\n`
            : '';
        const timeRangeLine = analysisContext.timeRange
            ? `- **Time Range:** ${analysisContext.timeRange}\n`
            : '';

        const content = `# Chart Analysis Report

## Chart Details

- **Metric:** ${analysisContext.metricDescription || 'N/A'}
${connectionLine}${databaseLine}${timeRangeLine}
---

${analysis}

---

*Generated by pgEdge AI DBA Workbench on ${new Date().toISOString()}*
`;

        downloadAsMarkdown(content, filename);
    };

    // Build icon
    const iconElement = <PsychologyIcon sx={getIconColorSx(theme)} />;

    // Build toolbar content
    const toolbarContent = (
        <>
            {/* Metric description */}
            <Typography sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>
                {analysisContext.metricDescription || 'Chart'}
            </Typography>

            {/* Connection pill */}
            {analysisContext.connectionName && (
                <Box sx={getConnectionBadgeSx(theme)}>
                    <Typography sx={sxMonoSmall}>
                        {analysisContext.connectionName}
                    </Typography>
                </Box>
            )}

            {/* Database pill */}
            {analysisContext.databaseName && (
                <Box sx={getDatabaseBadgeSx(theme)}>
                    <Typography sx={getDatabaseTextSx(theme)}>
                        {analysisContext.databaseName}
                    </Typography>
                </Box>
            )}

            {/* Time range */}
            {analysisContext.timeRange && (
                <Typography sx={{ fontSize: '0.875rem', color: 'text.disabled' }}>
                    {analysisContext.timeRange}
                </Typography>
            )}
        </>
    );

    return (
        <BaseAnalysisDialog
            open={open}
            onClose={onClose}
            title="Chart analysis"
            icon={iconElement}
            toolLabels={TOOL_LABELS}
            analysis={analysis}
            loading={loading}
            error={error}
            progressMessage={progressMessage}
            activeTools={activeTools}
            onDownload={handleDownload}
            toolbarContent={toolbarContent}
            markdownContent={
                analysis
                    ? `# Chart Analysis: ${analysisContext.metricDescription || 'Chart'}\n\n${analysis}`
                    : undefined
            }
            markdownContentProps={{
                isDark,
                connectionId: analysisContext.connectionId,
                databaseName: analysisContext.databaseName,
                serverName: analysisContext.connectionName,
            }}
        />
    );
};

export { ChartAnalysisDialog };
export default ChartAnalysisDialog;
