/*-------------------------------------------------------------------------
 *
 * pgEdge AI DBA Workbench - Query Analysis Dialog
 *
 * Copyright (c) 2025 - 2026, pgEdge, Inc.
 * This software is released under The PostgreSQL License
 *
 * Dialog component for displaying AI-powered query performance analysis
 * with professional analytics aesthetic and markdown rendering
 *
 *-------------------------------------------------------------------------
 */

import React, { useEffect, useRef } from 'react';
import { Box, Typography, useTheme } from '@mui/material';
import { Psychology as PsychologyIcon } from '@mui/icons-material';
import {
    useQueryAnalysis,
    QueryAnalysisInput,
} from '../hooks/useQueryAnalysis';
import { formatTime } from '../utils/formatters';
import { slugify } from '../utils/textHelpers';
import { getIconColorSx } from './shared/MarkdownExports';
import {
    getConnectionBadgeSx,
    getDatabaseBadgeSx,
    getDatabaseTextSx,
    sxMonoSmall,
} from './analysisStyles';
import { BaseAnalysisDialog } from './shared/BaseAnalysisDialog';
import { downloadAsMarkdown } from '../utils/downloadMarkdown';

const TOOL_LABELS = [
    'Querying metrics',
    'Fetching metric baselines',
    'Querying database',
    'Inspecting schema',
    'Validating query',
    'Searching knowledgebase',
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface QueryAnalysisDialogProps {
    open: boolean;
    onClose: () => void;
    isDark: boolean;
    queryText: string;
    queryId: string;
    stats: {
        calls: number;
        totalExecTime: number;
        meanExecTime: number;
        rows: number;
        sharedBlksHit: number;
        sharedBlksRead: number;
    };
    connectionId: number;
    connectionName?: string;
    databaseName: string;
}

const QueryAnalysisDialog: React.FC<QueryAnalysisDialogProps> = ({
    open,
    onClose,
    isDark,
    queryText,
    queryId,
    stats,
    connectionId,
    connectionName,
    databaseName,
}) => {
    const theme = useTheme();
    const { analysis, loading, error, progressMessage, activeTools, analyze } =
        useQueryAnalysis();

    // Trigger analysis once when dialog opens; ignore subsequent changes
    // while the dialog remains open.
    const hasTriggeredRef = useRef(false);

    useEffect(() => {
        if (open && !hasTriggeredRef.current) {
            hasTriggeredRef.current = true;
            if (!analysis) {
                const input: QueryAnalysisInput = {
                    queryText,
                    queryId,
                    calls: stats.calls,
                    totalExecTime: stats.totalExecTime,
                    meanExecTime: stats.meanExecTime,
                    rows: stats.rows,
                    sharedBlksHit: stats.sharedBlksHit,
                    sharedBlksRead: stats.sharedBlksRead,
                    connectionId,
                    databaseName,
                };
                analyze(input);
            }
        }
        if (!open) {
            hasTriggeredRef.current = false;
        }
    }, [open, analysis, queryText, queryId, stats, connectionId,
        databaseName, analyze]);

    // Download analysis as markdown file
    const handleDownload = () => {
        if (!analysis) { return; }

        const timestamp = new Date().toISOString().split('T')[0];
        const slug = slugify(queryId || 'query');
        const filename = `query-analysis-${slug}-${timestamp}.md`;

        const connectionLine = connectionName
            ? `- **Connection:** ${connectionName}\n`
            : '';
        const databaseLine = databaseName
            ? `- **Database:** ${databaseName}\n`
            : '';

        const content = `# Query Analysis Report

## Query Details

- **Query ID:** ${queryId}
${connectionLine}${databaseLine}- **Total Calls:** ${stats.calls.toLocaleString()}
- **Total Execution Time:** ${formatTime(stats.totalExecTime)}
- **Mean Execution Time:** ${formatTime(stats.meanExecTime)}

### Query Text

\`\`\`sql
${queryText}
\`\`\`

---

${analysis}

---

*Generated by pgEdge AI DBA Workbench on ${new Date().toISOString()}*
`;

        downloadAsMarkdown(content, filename);
    };

    // Build icon
    const iconElement = <PsychologyIcon sx={getIconColorSx(theme)} />;

    // Build toolbar content
    const toolbarContent = (
        <>
            {/* Connection pill */}
            {connectionName && (
                <Box sx={getConnectionBadgeSx(theme)}>
                    <Typography sx={sxMonoSmall}>
                        {connectionName}
                    </Typography>
                </Box>
            )}

            {/* Database pill */}
            {databaseName && (
                <Box sx={getDatabaseBadgeSx(theme)}>
                    <Typography sx={getDatabaseTextSx(theme)}>
                        {databaseName}
                    </Typography>
                </Box>
            )}
        </>
    );

    return (
        <BaseAnalysisDialog
            open={open}
            onClose={onClose}
            title="Query analysis"
            icon={iconElement}
            toolLabels={TOOL_LABELS}
            analysis={analysis}
            loading={loading}
            error={error}
            progressMessage={progressMessage}
            activeTools={activeTools}
            onDownload={handleDownload}
            toolbarContent={toolbarContent}
            markdownContent={
                analysis ? `# Query Analysis\n\n${analysis}` : undefined
            }
            markdownContentProps={{
                isDark,
                connectionId,
                databaseName,
                serverName: connectionName,
            }}
        />
    );
};

export { QueryAnalysisDialog };
export default QueryAnalysisDialog;
