/*-------------------------------------------------------------------------
 *
 * pgEdge AI DBA Workbench
 *
 * Copyright (c) 2025 - 2026, pgEdge, Inc.
 * This software is released under The PostgreSQL License
 *
 *-------------------------------------------------------------------------
 */

import type React from 'react';
import { useEffect, useMemo } from 'react';
import { Box, Typography, useTheme } from '@mui/material';
import {
    Psychology as PsychologyIcon,
    Storage as ServerIcon,
    Dns as ClusterIcon,
} from '@mui/icons-material';
import {
    useServerAnalysis,
} from '../hooks/useServerAnalysis';
import type { ServerSelection, ClusterSelection } from '../types/selection';
import { getIconColorSx } from './shared/MarkdownExports';
import { getServerBadgeSx, sxMonoSmall } from './analysisStyles';
import { BaseAnalysisDialog } from './shared/BaseAnalysisDialog';
import { downloadAsMarkdown } from '../utils/downloadMarkdown';

const TOOL_LABELS = [
    'Querying metrics',
    'Fetching metric baselines',
    'Reviewing alert history',
    'Checking alert rules',
    'Querying database',
    'Inspecting schema',
    'Listing probes',
    'Examining probe details',
    'Checking blackouts',
    'Validating query',
    'Searching knowledgebase',
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * ServerAnalysisDialog - Dialog for displaying AI-powered server/cluster analysis
 */
interface ServerAnalysisDialogProps {
    open: boolean;
    selection: (ServerSelection | ClusterSelection) | null;
    onClose: () => void;
}

const ServerAnalysisDialog: React.FC<ServerAnalysisDialogProps> = ({
    open,
    selection,
    onClose,
}) => {
    const theme = useTheme();
    const isDark = theme.palette.mode === 'dark';
    const {
        analysis,
        loading,
        error,
        progressMessage,
        activeTools,
        analyze,
        reset,
    } = useServerAnalysis();

    // Trigger analysis when dialog opens with a selection
    useEffect(() => {
        if (open && selection) {
            void analyze(selection);
        }
    }, [open, selection, analyze]);

    // Build connection map for cluster analysis
    const connectionMap = useMemo(() => {
        if (selection?.type !== 'cluster' || !selection.servers) {
            return undefined;
        }
        const map = new Map<number, string>();
        for (const server of selection.servers) {
            map.set(server.id, server.name);
        }
        return map;
    }, [selection]);

    // Download analysis as markdown file
    const handleDownload = () => {
        if (!analysis || !selection) { return; }

        const timestamp = new Date().toISOString().split('T')[0];
        const typeLabel = selection.type === 'cluster' ? 'cluster' : 'server';
        const filename = `${typeLabel}-analysis-${selection.name || 'unknown'}-${timestamp}.md`;

        let header = `# ${selection.type === 'cluster' ? 'Cluster' : 'Server'} Analysis Report\n\n`;
        header += `## Details\n\n`;
        header += `- **Name:** ${selection.name || 'N/A'}\n`;
        header += `- **Type:** ${selection.type === 'cluster' ? 'Cluster' : 'Server'}\n`;
        if (selection.type === 'cluster' && selection.servers) {
            header += `- **Servers:** ${selection.servers.map(s => s.name).join(', ')}\n`;
        }
        header += '\n---\n\n';

        const content = `${header}${analysis}\n\n---\n\n*Generated by pgEdge AI DBA Workbench on ${new Date().toISOString()}*\n`;

        downloadAsMarkdown(content, filename);
    };

    const isCluster = selection?.type === 'cluster';
    const TypeIcon = isCluster ? ClusterIcon : ServerIcon;

    // Build icon
    const iconElement = <PsychologyIcon sx={getIconColorSx(theme)} />;

    // Build toolbar content
    const toolbarContent = (
        <>
            {/* Name pill */}
            <Box sx={getServerBadgeSx(theme)}>
                <TypeIcon sx={{ fontSize: 14, color: 'text.secondary' }} />
                <Typography sx={sxMonoSmall}>
                    {selection?.name || 'Unknown'}
                </Typography>
            </Box>

            {/* Server count for clusters */}
            {isCluster && selection?.servers && (
                <Typography sx={{ fontSize: '0.875rem', color: 'text.disabled' }}>
                    {selection.servers.length} server{selection.servers.length !== 1 ? 's' : ''}
                </Typography>
            )}
        </>
    );

    return (
        <BaseAnalysisDialog
            open={open}
            onClose={onClose}
            title={isCluster ? 'Cluster analysis' : 'Server analysis'}
            icon={iconElement}
            toolLabels={TOOL_LABELS}
            analysis={analysis}
            loading={loading}
            error={error}
            progressMessage={progressMessage}
            activeTools={activeTools}
            onDownload={handleDownload}
            onReset={reset}
            toolbarContent={toolbarContent}
            markdownContent={
                analysis
                    ? `# ${selection?.type === 'cluster' ? 'Cluster' : 'Server'} Analysis: ${selection?.name || 'Unknown'}\n\n${analysis}`
                    : undefined
            }
            markdownContentProps={{
                isDark,
                connectionId:
                    selection?.type === 'server'
                        ? selection.id
                        : undefined,
                serverName:
                    selection?.type === 'server' ? selection.name : undefined,
                connectionMap,
            }}
        />
    );
};

export default ServerAnalysisDialog;
