/*-------------------------------------------------------------------------
 *
 * pgEdge AI DBA Workbench
 *
 * Copyright (c) 2025 - 2026, pgEdge, Inc.
 * This software is released under The PostgreSQL License
 *
 *-------------------------------------------------------------------------
 */
package notifications

import (
	"bytes"
	"encoding/json"
	"fmt"
	htmltemplate "html/template"
	"strings"
	"sync"
	"text/template"
	"time"

	"github.com/pgedge/ai-workbench/alerter/internal/database"
)

// Default Slack/Mattermost templates
const (
	DefaultSlackAlertFireTemplate = `{"text":"🚨 Alert: {{.AlertTitle}}","attachments":[{"color":"{{.SeverityColor}}","fields":[{"title":"Server","value":"{{.ServerName}} ({{.ServerHost}}:{{.ServerPort}})","short":true},{"title":"Severity","value":"{{.Severity}}","short":true}{{if .DatabaseName}},{"title":"Database","value":"{{.DatabaseName}}","short":true}{{end}}{{if .MetricName}},{"title":"Metric","value":"{{.MetricName}}","short":true}{{end}}],"text":"{{.AlertDescription}}"}]}`

	DefaultSlackAlertClearTemplate = `{"text":"✅ Resolved: {{.AlertTitle}}","attachments":[{"color":"#28a745","fields":[{"title":"Server","value":"{{.ServerName}}","short":true},{"title":"Duration","value":"{{.Duration}}","short":true}]}]}`

	DefaultSlackReminderTemplate = `{"text":"⏰ Reminder: {{.AlertTitle}} is still active","attachments":[{"color":"{{.SeverityColor}}","fields":[{"title":"Server","value":"{{.ServerName}}","short":true},{"title":"Active Since","value":"{{.TriggeredAt.Format "2006-01-02 15:04 MST"}}","short":true},{"title":"Reminder #","value":"{{.ReminderCount}}","short":true}]}]}`
)

// Default email templates (HTML)
const (
	DefaultEmailAlertFireTemplate = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Alert: {{.AlertTitle}}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .header { background-color: {{.SeverityColor}}; color: white; padding: 20px; }
        .header h1 { margin: 0; font-size: 20px; }
        .content { padding: 20px; }
        .field { margin-bottom: 12px; }
        .field-label { font-weight: 600; color: #666; font-size: 12px; text-transform: uppercase; }
        .field-value { font-size: 14px; color: #333; margin-top: 4px; }
        .footer { padding: 15px 20px; background-color: #f9f9f9; border-top: 1px solid #eee; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{.SeverityEmoji}} Alert: {{.AlertTitle}}</h1>
        </div>
        <div class="content">
            <div class="field">
                <div class="field-label">Description</div>
                <div class="field-value">{{.AlertDescription}}</div>
            </div>
            <div class="field">
                <div class="field-label">Server</div>
                <div class="field-value">{{.ServerName}} ({{.ServerHost}}:{{.ServerPort}})</div>
            </div>
            <div class="field">
                <div class="field-label">Severity</div>
                <div class="field-value">{{.Severity}}</div>
            </div>
            {{if .DatabaseName}}<div class="field">
                <div class="field-label">Database</div>
                <div class="field-value">{{.DatabaseName}}</div>
            </div>{{end}}
            {{if .MetricName}}<div class="field">
                <div class="field-label">Metric</div>
                <div class="field-value">{{.MetricName}}{{if .MetricValue}}: {{.MetricValue}}{{end}}{{if .ThresholdValue}} (threshold: {{.Operator}} {{.ThresholdValue}}){{end}}</div>
            </div>{{end}}
            <div class="field">
                <div class="field-label">Triggered At</div>
                <div class="field-value">{{.TriggeredAt.Format "2006-01-02 15:04:05 MST"}}</div>
            </div>
        </div>
        <div class="footer">
            This alert was generated by pgEdge AI DBA Workbench.
        </div>
    </div>
</body>
</html>`

	DefaultEmailAlertClearTemplate = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Resolved: {{.AlertTitle}}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .header { background-color: #28a745; color: white; padding: 20px; }
        .header h1 { margin: 0; font-size: 20px; }
        .content { padding: 20px; }
        .field { margin-bottom: 12px; }
        .field-label { font-weight: 600; color: #666; font-size: 12px; text-transform: uppercase; }
        .field-value { font-size: 14px; color: #333; margin-top: 4px; }
        .footer { padding: 15px 20px; background-color: #f9f9f9; border-top: 1px solid #eee; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>✅ Resolved: {{.AlertTitle}}</h1>
        </div>
        <div class="content">
            <div class="field">
                <div class="field-label">Server</div>
                <div class="field-value">{{.ServerName}} ({{.ServerHost}}:{{.ServerPort}})</div>
            </div>
            <div class="field">
                <div class="field-label">Duration</div>
                <div class="field-value">{{.Duration}}</div>
            </div>
            <div class="field">
                <div class="field-label">Triggered At</div>
                <div class="field-value">{{.TriggeredAt.Format "2006-01-02 15:04:05 MST"}}</div>
            </div>
            {{if .ClearedAt}}<div class="field">
                <div class="field-label">Cleared At</div>
                <div class="field-value">{{.ClearedAt.Format "2006-01-02 15:04:05 MST"}}</div>
            </div>{{end}}
        </div>
        <div class="footer">
            This notification was generated by pgEdge AI DBA Workbench.
        </div>
    </div>
</body>
</html>`

	DefaultEmailReminderTemplate = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Reminder: {{.AlertTitle}}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background-color: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .header { background-color: {{.SeverityColor}}; color: white; padding: 20px; }
        .header h1 { margin: 0; font-size: 20px; }
        .content { padding: 20px; }
        .field { margin-bottom: 12px; }
        .field-label { font-weight: 600; color: #666; font-size: 12px; text-transform: uppercase; }
        .field-value { font-size: 14px; color: #333; margin-top: 4px; }
        .reminder-badge { display: inline-block; background-color: #ffc107; color: #000; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
        .footer { padding: 15px 20px; background-color: #f9f9f9; border-top: 1px solid #eee; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>⏰ Reminder: {{.AlertTitle}}</h1>
        </div>
        <div class="content">
            <p><span class="reminder-badge">Reminder #{{.ReminderCount}}</span></p>
            <div class="field">
                <div class="field-label">Description</div>
                <div class="field-value">{{.AlertDescription}}</div>
            </div>
            <div class="field">
                <div class="field-label">Server</div>
                <div class="field-value">{{.ServerName}} ({{.ServerHost}}:{{.ServerPort}})</div>
            </div>
            <div class="field">
                <div class="field-label">Severity</div>
                <div class="field-value">{{.Severity}}</div>
            </div>
            <div class="field">
                <div class="field-label">Active Since</div>
                <div class="field-value">{{.TriggeredAt.Format "2006-01-02 15:04:05 MST"}}</div>
            </div>
        </div>
        <div class="footer">
            This reminder was generated by pgEdge AI DBA Workbench.
        </div>
    </div>
</body>
</html>`
)

// Default webhook templates (JSON)
const (
	DefaultWebhookAlertFireTemplate = `{"event":"alert_fire","alert_id":{{.AlertID}},"title":"{{.AlertTitle}}","description":"{{.AlertDescription}}","severity":"{{.Severity}}","server":{"name":"{{.ServerName}}","host":"{{.ServerHost}}","port":{{.ServerPort}}}{{if .DatabaseName}},"database":"{{.DatabaseName}}"{{end}}{{if .MetricName}},"metric":{"name":"{{.MetricName}}"{{if .MetricValue}},"value":{{.MetricValue}}{{end}}{{if .ThresholdValue}},"threshold":{{.ThresholdValue}}{{end}}{{if .Operator}},"operator":"{{.Operator}}"{{end}}}{{end}},"triggered_at":"{{.TriggeredAt.Format "2006-01-02T15:04:05Z07:00"}}"}`

	DefaultWebhookAlertClearTemplate = `{"event":"alert_clear","alert_id":{{.AlertID}},"title":"{{.AlertTitle}}","server":{"name":"{{.ServerName}}","host":"{{.ServerHost}}","port":{{.ServerPort}}},"triggered_at":"{{.TriggeredAt.Format "2006-01-02T15:04:05Z07:00"}}"{{if .ClearedAt}},"cleared_at":"{{.ClearedAt.Format "2006-01-02T15:04:05Z07:00"}}"{{end}},"duration":"{{.Duration}}"}`

	DefaultWebhookReminderTemplate = `{"event":"reminder","alert_id":{{.AlertID}},"title":"{{.AlertTitle}}","description":"{{.AlertDescription}}","severity":"{{.Severity}}","server":{"name":"{{.ServerName}}","host":"{{.ServerHost}}","port":{{.ServerPort}}},"triggered_at":"{{.TriggeredAt.Format "2006-01-02T15:04:05Z07:00"}}","reminder_count":{{.ReminderCount}}}`
)

// Severity colors for templates
const (
	SeverityColorCritical = "#dc3545"
	SeverityColorHigh     = "#fd7e14"
	SeverityColorWarning  = "#ffc107"
	SeverityColorInfo     = "#17a2b8"
)

// Severity emojis for templates
const (
	SeverityEmojiCritical = "🔴"
	SeverityEmojiHigh     = "🟠"
	SeverityEmojiWarning  = "🟡"
	SeverityEmojiInfo     = "🔵"
)

// templateRenderer implements TemplateRenderer
type templateRenderer struct {
	cache     sync.Map // caches compiled *template.Template by template string
	htmlCache sync.Map // caches compiled *htmltemplate.Template by template string
}

// NewTemplateRenderer creates a new TemplateRenderer
func NewTemplateRenderer() TemplateRenderer {
	return &templateRenderer{}
}

// Render implements TemplateRenderer.Render
func (r *templateRenderer) Render(templateStr string, payload *database.NotificationPayload, defaultTemplate string) (string, error) {
	// Use defaultTemplate if templateStr is empty
	tmplStr := templateStr
	if tmplStr == "" {
		tmplStr = defaultTemplate
	}

	if tmplStr == "" {
		return "", fmt.Errorf("no template provided")
	}

	// Create enhanced data map with computed fields
	data := r.enhancePayload(payload)

	// Use html/template for HTML content to prevent XSS
	if isHTMLTemplate(tmplStr) {
		tmpl, err := r.getOrCompileHTMLTemplate(tmplStr)
		if err != nil {
			return "", fmt.Errorf("failed to compile HTML template: %w", err)
		}

		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, data); err != nil {
			return "", fmt.Errorf("failed to execute HTML template: %w", err)
		}
		return buf.String(), nil
	}

	// Use text/template for plain text content
	tmpl, err := r.getOrCompileTemplate(tmplStr)
	if err != nil {
		return "", fmt.Errorf("failed to compile template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// RenderJSON implements TemplateRenderer.RenderJSON
// Unlike Render, this method JSON-escapes all string values in the
// template data before executing the template.  This ensures that
// descriptions or titles containing characters that are special in
// JSON (double quotes, backslashes, backticks, newlines, etc.) do
// not break the rendered JSON payload.
func (r *templateRenderer) RenderJSON(templateStr string, payload *database.NotificationPayload, defaultTemplate string) (string, error) {
	// Use defaultTemplate if templateStr is empty
	tmplStr := templateStr
	if tmplStr == "" {
		tmplStr = defaultTemplate
	}

	if tmplStr == "" {
		return "", fmt.Errorf("no template provided")
	}

	// Get or compile template from cache
	tmpl, err := r.getOrCompileTemplate(tmplStr)
	if err != nil {
		return "", fmt.Errorf("failed to compile template: %w", err)
	}

	// Create enhanced data map and JSON-escape all string values
	data := r.enhancePayload(payload)
	jsonEscapeStringValues(data)

	// Execute template
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	result := buf.String()

	// Validate result is valid JSON
	var js json.RawMessage
	if err := json.Unmarshal([]byte(result), &js); err != nil {
		return "", fmt.Errorf("rendered template is not valid JSON: %w", err)
	}

	return result, nil
}

// jsonEscapeStringValues iterates over a map and replaces every
// string value with its JSON-escaped form (without surrounding
// quotes).  Non-string values are left unchanged.
func jsonEscapeStringValues(data map[string]any) {
	for k, v := range data {
		if s, ok := v.(string); ok {
			data[k] = jsonEscapeString(s)
		}
	}
}

// jsonEscapeString returns the JSON-escaped form of s, without
// the surrounding double-quote characters that json.Marshal adds.
// For example, a string containing a literal double-quote becomes
// \" in the output, and a newline becomes \n.
func jsonEscapeString(s string) string {
	b, err := json.Marshal(s)
	if err != nil {
		// json.Marshal on a string should never fail, but return
		// the original string unmodified if it somehow does.
		return s
	}
	// json.Marshal wraps the result in double quotes; strip them.
	return string(b[1 : len(b)-1])
}

// isHTMLTemplate returns true if the template content appears to be HTML.
func isHTMLTemplate(templateStr string) bool {
	trimmed := strings.TrimSpace(templateStr)
	lower := strings.ToLower(trimmed)
	return strings.HasPrefix(lower, "<!doctype html") ||
		strings.HasPrefix(lower, "<html") ||
		strings.HasPrefix(lower, "<body") ||
		strings.HasPrefix(lower, "<div")
}

// getOrCompileTemplate retrieves a compiled text template from the cache or compiles it
func (r *templateRenderer) getOrCompileTemplate(templateStr string) (*template.Template, error) {
	// Check cache first
	if cached, ok := r.cache.Load(templateStr); ok {
		tmpl, ok := cached.(*template.Template)
		if !ok {
			return nil, fmt.Errorf("cached template has unexpected type %T", cached)
		}
		return tmpl, nil
	}

	// Compile template
	tmpl, err := template.New("notification").Parse(templateStr)
	if err != nil {
		return nil, err
	}

	// Store in cache
	r.cache.Store(templateStr, tmpl)

	return tmpl, nil
}

// getOrCompileHTMLTemplate retrieves a compiled HTML template from the cache or compiles it.
// HTML templates automatically escape dynamic values to prevent XSS.
func (r *templateRenderer) getOrCompileHTMLTemplate(templateStr string) (*htmltemplate.Template, error) {
	// Check cache first
	if cached, ok := r.htmlCache.Load(templateStr); ok {
		tmpl, ok := cached.(*htmltemplate.Template)
		if !ok {
			return nil, fmt.Errorf("cached HTML template has unexpected type %T", cached)
		}
		return tmpl, nil
	}

	// Compile template
	tmpl, err := htmltemplate.New("notification").Parse(templateStr)
	if err != nil {
		return nil, err
	}

	// Store in cache
	r.htmlCache.Store(templateStr, tmpl)

	return tmpl, nil
}

// enhancePayload creates a map with all payload fields plus computed fields
func (r *templateRenderer) enhancePayload(p *database.NotificationPayload) map[string]any {
	data := map[string]any{
		// Alert info
		"AlertID":          p.AlertID,
		"AlertType":        p.AlertType,
		"AlertTitle":       p.AlertTitle,
		"AlertDescription": p.AlertDescription,
		"Severity":         p.Severity,
		"Status":           p.Status,
		"TriggeredAt":      p.TriggeredAt,
		"ClearedAt":        p.ClearedAt,

		// Server info
		"ConnectionID": p.ConnectionID,
		"ServerName":   p.ServerName,
		"ServerHost":   p.ServerHost,
		"ServerPort":   p.ServerPort,

		// Notification info
		"NotificationType": p.NotificationType,
		"ReminderCount":    p.ReminderCount,
		"Timestamp":        p.Timestamp,
	}

	// Add optional fields only if they have values
	if p.MetricName != nil {
		data["MetricName"] = *p.MetricName
	}
	if p.MetricValue != nil {
		data["MetricValue"] = *p.MetricValue
	}
	if p.ThresholdValue != nil {
		data["ThresholdValue"] = *p.ThresholdValue
	}
	if p.Operator != nil {
		data["Operator"] = *p.Operator
	}
	if p.DatabaseName != nil {
		data["DatabaseName"] = *p.DatabaseName
	}

	// Add computed fields
	// Duration - if ClearedAt is set, format the duration since TriggeredAt
	if p.ClearedAt != nil {
		duration := p.ClearedAt.Sub(p.TriggeredAt)
		data["Duration"] = formatDuration(duration)
	} else if p.Duration != nil {
		data["Duration"] = *p.Duration
	} else {
		data["Duration"] = ""
	}

	// SeverityColor - return color hex based on severity
	data["SeverityColor"] = getSeverityColor(p.Severity)

	// SeverityEmoji - return emoji based on severity
	data["SeverityEmoji"] = getSeverityEmoji(p.Severity)

	return data
}

// formatDuration formats a duration in a human-readable way
func formatDuration(d time.Duration) string {
	if d < 0 {
		d = -d
	}

	days := int(d.Hours() / 24)
	hours := int(d.Hours()) % 24
	minutes := int(d.Minutes()) % 60
	seconds := int(d.Seconds()) % 60

	if days > 0 {
		return fmt.Sprintf("%dd %dh", days, hours)
	}
	if hours > 0 {
		return fmt.Sprintf("%dh %dm", hours, minutes)
	}
	if minutes > 0 {
		return fmt.Sprintf("%dm %ds", minutes, seconds)
	}
	return fmt.Sprintf("%ds", seconds)
}

// getSeverityColor returns the hex color for a severity level
func getSeverityColor(severity string) string {
	switch severity {
	case "critical":
		return SeverityColorCritical
	case "high":
		return SeverityColorHigh
	case "warning":
		return SeverityColorWarning
	case "info":
		return SeverityColorInfo
	default:
		return SeverityColorInfo
	}
}

// getSeverityEmoji returns the emoji for a severity level
func getSeverityEmoji(severity string) string {
	switch severity {
	case "critical":
		return SeverityEmojiCritical
	case "high":
		return SeverityEmojiHigh
	case "warning":
		return SeverityEmojiWarning
	case "info":
		return SeverityEmojiInfo
	default:
		return SeverityEmojiInfo
	}
}
