version: "2"
run:
  tests: true
linters:
  enable:
    - gosec
    - misspell
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value of.*Close.*not checked
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
